system:
  name: K1 多层视觉分拣系统
  model_path: /home/bianbu/1/ai-sdk/models/my_yolov11m/model/best_yolov11n_int8_fix.q.onnx
  labels_path: /home/bianbu/1/ai-sdk/models/my_yolov11m/data/label.txt
  camera_width: 640
  camera_height: 480
  camera_fps: 30
  camera_cache_size: 2
  conf_threshold: 0.15
  nms_iou: 0.45
  topk: 100
  warmup_runs: 10
  camera_scan_max_index: 64
  jpeg_quality: 80
layers:
- id: layer_1
  name: 第一层
  enabled: true
  camera_uid: camera-2a75ce5cf22549f9
  camera_path: /dev/video20
  pwm_uid: pwm-0a4fdd646ad5537e
  pwm_chip: /sys/class/pwm/pwmchip0
  pwm_channel: 0
  target_color: red
  non_target_action: other
  trigger_line: 400
  flow_direction: 1
  control_conf: 0.45
  min_hits: 2
  track_iou: 0.3
  track_max_age: 12
  startup_delay: 2.0
  infer_interval_ms: 40
  servo:
    enabled: true
    period_ns: 5000000
    min_duty_ns: 1100000
    max_duty_ns: 1900000
    init_duty_ns: 1500000
    reset_duty_ns: 1500000
    target_duty_ns: 1630000
    other_duty_ns: 1370000
    hold_seconds: 2
    smooth_steps: 15
    smooth_delay: 0.01
    queue_size: 20
  target_duty_ns: 1630000
  reset_duty_ns: 1500000
  other_duty_ns: 1370000
  hold_seconds: 2
- id: layer_2
  name: 第二层
  enabled: true
  camera_uid: camera-70442b3743327b2f
  camera_path: /dev/video22
  pwm_uid: pwm-13a3a47c6a6a19ea
  pwm_chip: /sys/class/pwm/pwmchip2
  pwm_channel: 0
  target_color: yellow
  non_target_action: other
  trigger_line: 400
  flow_direction: 1
  control_conf: 0.45
  min_hits: 2
  track_iou: 0.3
  track_max_age: 12
  startup_delay: 2.0
  infer_interval_ms: 40
  servo:
    enabled: true
    period_ns: 5000000
    min_duty_ns: 1100000
    max_duty_ns: 1900000
    init_duty_ns: 1500000
    reset_duty_ns: 1500000
    target_duty_ns: 1630000
    other_duty_ns: 1370000
    hold_seconds: 2
    smooth_steps: 15
    smooth_delay: 0.01
    queue_size: 20
  target_duty_ns: 1630000
  reset_duty_ns: 1500000
  other_duty_ns: 1370000
  hold_seconds: 2
- id: layer_3
  name: 第三层
  enabled: true
  camera_uid: camera-23f77d28262f5467
  camera_path: /dev/video24
  pwm_uid: pwm-bb2c6534057ebb4e
  pwm_chip: /sys/class/pwm/pwmchip1
  pwm_channel: 0
  target_color: blue
  non_target_action: other
  trigger_line: 300
  flow_direction: 1
  control_conf: 0.45
  min_hits: 2
  track_iou: 0.3
  track_max_age: 12
  startup_delay: 2.0
  infer_interval_ms: 40
  servo:
    enabled: true
    period_ns: 5000000
    min_duty_ns: 1100000
    max_duty_ns: 1900000
    init_duty_ns: 1500000
    reset_duty_ns: 1500000
    target_duty_ns: 1630000
    other_duty_ns: 1370000
    hold_seconds: 2
    smooth_steps: 15
    smooth_delay: 0.01
    queue_size: 20
  target_duty_ns: 1630000
  reset_duty_ns: 1500000
  other_duty_ns: 1370000
  hold_seconds: 2
- id: layer_4
  name: 第四层
  enabled: true
  camera_uid: camera-91d0f1e618bad4a0
  camera_path: /dev/video20
  pwm_uid: pwm-a5ab1e06df681ad8
  pwm_chip: /sys/class/pwm/pwmchip3
  pwm_channel: 0
  target_color: green
  non_target_action: other
  trigger_line: 300
  flow_direction: 1
  control_conf: 0.45
  min_hits: 2
  track_iou: 0.3
  track_max_age: 12
  startup_delay: 2.0
  infer_interval_ms: 40
  servo:
    enabled: true
    period_ns: 5000000
    min_duty_ns: 1100000
    max_duty_ns: 1900000
    init_duty_ns: 1500000
    reset_duty_ns: 1500000
    target_duty_ns: 1630000
    other_duty_ns: 1370000
    hold_seconds: 2
    smooth_steps: 15
    smooth_delay: 0.01
    queue_size: 20
  target_duty_ns: 1630000
  reset_duty_ns: 1500000
  other_duty_ns: 1370000
  hold_seconds: 2
